package org.phenoapps.intercross.fragments.preferences

class GeneralKeys {
    companion object {
        val INTERCROSS_PREFIX = "org.phenoapps.intercross."

        // PROFILE PREFERENCES
        val FIRST_NAME = INTERCROSS_PREFIX + "FIRST_NAME"
        val LAST_NAME = INTERCROSS_PREFIX + "LAST_NAME"
        val REQUIRE_USER_TO_COLLECT = INTERCROSS_PREFIX + "REQUIRE_USER_TO_COLLECT"
        val REQUIRE_USER_INTERVAL = INTERCROSS_PREFIX + "REQUIRE_USER_INTERVAL"

        val LAST_TIME_ASKED = INTERCROSS_PREFIX + "LAST_TIME_OPENED"
        val ASKED_SINCE_OPENED = INTERCROSS_PREFIX + "ASKED_SINCE_OPENED"
        val MODIFY_PROFILE_SETTINGS = "MODIFY_PROFILE_SETTINGS"
        val PERSON_UPDATE = "PERSON_UPDATE"

        val EXPERIMENT_NAME = INTERCROSS_PREFIX + "EXPERIMENT_NAME"

        // PRINTING PREFERENCES
        val ZPL_CODE = INTERCROSS_PREFIX + "ZPL_CODE"

        // BEHAVIOR PREFERENCES
        // Naming
        val BLANK_MALE_ID = INTERCROSS_PREFIX + "BLANK_MALE_ID"
        val CROSS_ORDER = INTERCROSS_PREFIX + "CROSS_ORDER"
        val CREATE_PATTERN = INTERCROSS_PREFIX + "CREATE_PATTERN"
        // Workflow
        val COLLECT_INFO = INTERCROSS_PREFIX + "COLLECT_INFO"
        val META_DATA = INTERCROSS_PREFIX + "META_DATA"
        val META_DATA_DEFAULTS = INTERCROSS_PREFIX + "META_DATA_DEFAULTS"
        val SOUND_NOTIFICATIONS = INTERCROSS_PREFIX + "SOUND_NOTIFICATIONS"
        val OPEN_CROSS_IMMEDIATELY = INTERCROSS_PREFIX + "OPEN_CROSS_IMMEDIATELY"
        val COMMUTATIVE_CROSSING = INTERCROSS_PREFIX + "COMMUTATIVE_CROSSING"


        // val COMMUTATIVE_CROSSING = INTERCROSS_PREFIX + "BLANK_MALE_ID"

        // BRAPI PREFERENCES
        const val BRAPI_ENABLED = "org.phenoapps.intercross.BRAPI_ENABLED"
        const val BRAPI_BASE_URL = "org.phenoapps.intercross.BRAPI_BASE_URL"
        const val BRAPI_PAGE_SIZE = "1000"
        const val BRAPI_TOKEN = "org.phenoapps.intercross.BRAPI_TOKEN"
        const val BRAPI_VERSION = "2"
        const val BRAPI_DISPLAY_NAME = "org.phenoapps.intercross.BRAPI_DISPLAY_NAME"
    }
}